events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    types {
        application/javascript  js mjs;
    }
    default_type  application/octet-stream;
    
    client_max_body_size 500M;

    server {
        listen 80;
        server_name localhost;

        location /api/uploads/covers/ {
            alias /var/www/static/uploads/covers/;
            add_header Accept-Ranges bytes;
            add_header Access-Control-Allow-Origin *;
            expires 30d;
        }
        location /api/uploads/pdfs/ {
            alias /var/www/static/uploads/pdfs/;
            add_header Accept-Ranges bytes;
            add_header Access-Control-Allow-Origin *;
        }
        location /api/uploads/videos/ {
            alias /var/www/static/uploads/videos/;
            add_header Accept-Ranges bytes;
            add_header Access-Control-Allow-Origin *;
        }

        location / {
            root /var/www/frontend;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
            proxy_cache off;
            proxy_http_version 1.1;
            proxy_read_timeout 300s;
        }
    }
}
